Issue 63
P7-Team/P7-Client pull request #84
Opened 2021-11-17 07:57 UTC by soenderby

closes #63

2021-11-17 13:31 UTC, Kaliahh requested changes

2021-11-17 13:31 UTC, Kaliahh commented on Client/Clients/TaskClient.cs
> +            HttpResponseMessage res = _client.Send(new HttpRequestMessage() { Content = content });
```suggestion
            // TODO: Refactor to use the new Post after merging
            HttpResponseMessage res = _client.Send(new HttpRequestMessage() { Content = content });
```

2021-11-17 13:31 UTC, Kaliahh commented on Client/Interfaces/IHttpClient.cs
```suggestion
using System.Net.Http;

```

2021-11-17 13:54 UTC, naitoarekkus reviewed
Der var et lille spørgsmål omkring ResultFile modellen.
Men jeg har skrevet en kommentar

2021-11-17 13:54 UTC, naitoarekkus commented on Client/Models/ResultFile.cs
> +        public string Name { get; }
Vil en result file ikke også skulle indeholder path'en?
Det er information vi også får ud af database

2021-11-17 13:58 UTC, naitoarekkus submitted a review, later dismissed
Approved

2021-11-17 13:59 UTC, Kaliahh submitted a review, later dismissed

2021-11-17 14:02 UTC, naitoarekkus approved these changes
Approved

2021-11-17 14:02 UTC, Kaliahh submitted a review, later dismissed

2021-11-18 07:18 UTC, naitoarekkus approved these changes
Approved

2021-11-18 07:32 UTC, Kaliahh approved these changes

2021-11-18 07:33 UTC, merged