#71 the requester client should be able to ask the web service for the results of its batch
P7-Team/P7-Client pull request #94
Opened 2021-12-06 08:24 UTC by zaztz

2021-12-06 11:41 UTC, dkalaxdk reviewed
Bliver multiparthHelper,Marshaller og sectionedDataReader brugt?

2021-12-06 12:14 UTC, AxialDark requested changes
Det ser umildbart fint ud, der er dog nogle rettelser som jeg mener skal laves for at følge standarderne vi har sat

2021-12-06 12:14 UTC, AxialDark commented on Client/Clients/BatchClient.cs
> +                List<BatchStatus> _batchStatuslist=  new List<BatchStatus>();
Så vidt jeg har forstået så følger dette ikke navne standarden "_" bliver kun brugt til private field variabler

2021-12-06 12:14 UTC, AxialDark commented on Client/Clients/BatchClient.cs
> +                foreach (BatchStatus _batchstatus in Result)
Så vidt jeg har forstået så følger dette ikke navne standarden "_" bliver kun brugt til private field variabler

2021-12-06 12:14 UTC, AxialDark commented on Client/Services/ClientStateManager.cs
> +            List<BatchStatus> batches = (List<BatchStatus>) _batchClient.GetBatchStatus();
Så vidt jeg kan se er castet til (List<BatchStatus>) ligegyldigt da _batchClient.GetBatchStatus(), allerede returnere det som en List<BatchStatus>

2021-12-06 12:14 UTC, AxialDark commented on Client-app unit tests/BatchClientTest.cs
> +}
Test navngivningen følger ikke rigtigt den navne standard som er brugt til andre tests
\<Tested Method\>\_(Optional)\<Precondition\>\_\<Expected Result\>
Uden klammerne selvfølgelig

2021-12-07 10:46 UTC, soenderby commented on Client-app unit tests/BatchClientTest.cs
> +using Client.Clients;
```suggestion
```

2021-12-07 10:47 UTC, soenderby commented on Client-app unit tests/BatchClientTest.cs
> +        public void GetBatcesStattusReady()
```suggestion
        public void GetBatchesStatusReady()
```

2021-12-07 10:51 UTC, soenderby commented on Client-app unit tests/BatchClientTest.cs
> +        public void GetBatchEnsureDiffence()
```suggestion
        public void GetBatchEnsureDifference()
```

2021-12-07 10:55 UTC, soenderby commented on Client-app unit tests/BatchClientTest.cs
> +        public void GetBatcesStattusContiaFourBathes()
```suggestion
        public void GetBatchesStatusContiaFourBatches()
```

2021-12-07 10:56 UTC, soenderby commented on Client/Clients/BatchClient.cs
> +using System;
```suggestion
```

2021-12-07 10:56 UTC, soenderby commented on Client/Clients/BatchClient.cs
> +using System.IO;
```suggestion
```

2021-12-07 10:58 UTC, soenderby commented on Client/Clients/BatchClient.cs
> +                        throw Anull;
Jeg vil også foreslå at der laves en catch på den Generelle Exception, i stedet for flere forskellige exceptions da de behandles ens

2021-12-07 11:41 UTC, soenderby approved these changes

2021-12-07 13:04 UTC, zaztz commented on Client/Clients/BatchClient.cs
> +                foreach (BatchStatus _batchstatus in Result)
Det er sandt og bliver rettet

2021-12-07 13:29 UTC, zaztz commented on Client-app unit tests/BatchClientTest.cs
> +        public void GetBatcesStattusReady()
Jeg har rename dem ud fra Alex kommentar

2021-12-07 13:42 UTC, zaztz commented on Client/Clients/BatchClient.cs
> +                        throw Anull;
så er der implementer det overstående

2021-12-07 13:55 UTC, zaztz commented on Client-app unit tests/BatchClientTest.cs
> +}
Jeg har renamet dem

2021-12-07 13:59 UTC, AxialDark approved these changes
Approved

2021-12-07 14:00 UTC, soenderby approved these changes

2021-12-07 14:01 UTC, merged